# NUMPY İLE ÇALIŞMAK

# Veri biliminde en çok kullanılan kütüphanedir.


In [2]:
lıstem=[1,2,3,4,5,6,7,9]

In [3]:
type(lıstem)

list

In [6]:
# numpy ile çalışmaya başlamadan önce ilk yapman gereken kütüphaneyi import etmendir.

In [7]:
import numpy as np

In [8]:
# yukarıda verilen listeyi bir numpy dizisine çevirelim
np.array(lıstem)

array([1, 2, 3, 4, 5, 6, 7, 9])

In [10]:
#eğer türüne bakmak istersen, türü nupy içinden türeyen bir nesnedir.
type(np.array(lıstem))

numpy.ndarray

In [11]:
#numpy da liste içinde liste ,dizi içinde dizi oluşturabilirsin.
#tipini sorgularsan eğer sana liste verecektir

In [12]:
matrixlıstesı=[[1,2,3],[4,5,6],[7,8,9]]

In [13]:
type(matrixlıstesı)

list

In [14]:
matrixlıstesı[1][0]

4

In [16]:
np.array(matrixlıstesı)
#listenin diziye çevrilmesi

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# NUMPY YÖNTEMLERİ

In [17]:
# ARANGE : range fonksiyonun aynısı tek farkı şudur : sana liste değilde dizi şeklinde oluşturuyor

In [18]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [19]:
np.array(range(0,10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.array(range(0,200,10))

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120,
       130, 140, 150, 160, 170, 180, 190])

In [23]:
#ZEROS : bildiğin 0 oluşturma yöntemidir.
np.zeros((9,9))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [24]:
#ONES:  1 oluşturma yöntemidir.
np.ones((9,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [25]:
#LİNSPACE : bu metot belirtilen numaralar arasında eşit olarak boyutlandırma yap demektir.
# örneğin 0-20 arasında 6 tane rakam seç ve 6 sınında uzaklığı birbirine eşit olsun

In [26]:
np.linspace(0,20,6)

array([ 0.,  4.,  8., 12., 16., 20.])

In [27]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [28]:
#EYE :Matrix oluşturur. diagonal bir yapısı vardır yani orta çubuk hep 1 olacak geri kalanları ise 0 olacaktır

np.eye(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
#RANDOM : random oluşturur l,ste yada dizi oluşturabilir
np.random.rand(6)

array([0.83184954, 0.46700702, 0.71894129, 0.8596919 , 0.02130575,
       0.30675448])

In [11]:
import numpy as np
np.random.rand(3,3)


array([[0.69220771, 0.47894404, 0.0147867 ],
       [0.85857901, 0.05715257, 0.41225324],
       [0.77370776, 0.77400814, 0.22494774]])

In [12]:
#1 ve 10 arasında 10 dahil değil 5 tane sayı üret bana
np.random.randint(1,10,5)

array([5, 4, 1, 3, 2])

In [13]:
numpyDızım=np.arange(30)

In [14]:
numpyDızım

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [15]:
numpyDızım.reshape(6,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [16]:
numpyDızım.max()

29

In [17]:
numpyDızım.min()

0

In [18]:
numpyDızım.argmax()
#en yüksek sayı kaçıncı indekste

29

In [19]:
numpyDızım.argmin()

0

In [20]:
numpyDızım.shape
#dizinin güncel şeklini görebilmeni sağlar

(30,)

In [22]:
#shape: şekil demek güncel dizimin hangi şekilde olduğunu ben  shape ile görebiliyorum
numpyDızım.shape

(30,)

In [25]:
numpyDızım.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

# # NUMPY İNDEKSLER

In [26]:
#Çekmek istediğin herhangi bir değer olduğunda sen bunu indeksler yardımı ile çekeceksin.

In [27]:
import numpy as np

In [31]:
dızımmm=np.arange(0,12)

In [32]:
dızımmm

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [33]:
dızımmm[5]

5

In [34]:
dızımmm[3:8]

array([3, 4, 5, 6, 7])

In [35]:
baskaDızı=np.arange(0,24)

In [36]:
baskaDızı

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [38]:
dıgerDızı=baskaDızı[3:9]

In [39]:
dıgerDızı

array([3, 4, 5, 6, 7, 8])

In [40]:
#örneğin ben tüm elemanların değerlerini 700 e eşitlemek istiyorum.
dıgerDızı[:]=700

In [41]:
dıgerDızı

array([700, 700, 700, 700, 700, 700])

In [42]:
#baska diziyi çağırısam eğer ordaki değerler de değişti
baskaDızı

array([  0,   1,   2, 700, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])